### ISSUE TITLE
yarn format fails, cannot commit to my clone of this project

### ISSUE THREAD

**Issue by alpiepho** [colbyfayock/gatsby-starter-leaflet#11]
I am following your FCC tutorial (Thanks for that) at https://www.freecodecamp.org/news/how-to-create-a-coronavirus-covid-19-dashboard-map-app-in-react-with-gatsby-and-leaflet/

I was trying to commit after Step1 and hit yarn format error with prettier-eslint that blocks commits to my local repo. (Error: 'basePath' should be an absolute path)

I found this link that describes add $PWD as part of the regex string.
https://github.com/prettier/prettier-eslint-cli/issues/208

I use Mac/Linux so I don't have the issue the link describes about Windows.

Thought you should know about this.  Thanks again for the FCC tutorial, can't wait to finish working thru it.

**Comment by colbyfayock** [comment]
ah!! thank you, and thank you for finding the fix. I just pushed up a change that fixed it for me locally by appending the `$PWD` like you said
