### ISSUE TITLE
Parsing error: The keyword 'import' is reserved

### ISSUE THREAD

**Issue by souljacker** [colbyfayock/gatsby-starter-leaflet#12]
There seems to be some error with babel configuration.

I'm having this error on my VSCODE on every file using import

**Comment by colbyfayock** [comment]
hey @souljacker would you mind creating a Github repository with your code so I can try to take a look?

**Comment by souljacker** [comment]
It's literally the one here, I just cloned

**Comment by colbyfayock** [comment]
strange - what version of node are you using? I'm not seeing any problems on my system

this was on v10.16.3

![image](https://user-images.githubusercontent.com/1045274/80661738-81a6b800-8a5d-11ea-9c46-08e52328c7f5.png)

**Comment by adisher** [comment]
`Parsing error: The keyword 'import' is reserved eslint`

A red line pops under the import keyword. It doesn't happen the first time I gatsby develop. 
Node: v12.18.1

@colbyfayock

**Comment by colbyfayock** [comment]
@souljacker @adisher still can't repro - but i found this: https://github.com/yannickcr/eslint-plugin-react/issues/448

I added `modules: true` to the eslint config, can you see if that helps?

**Comment by colbyfayock** [comment]
hey checking in here - any luck?

**Comment by colbyfayock** [comment]
going to close this - please let me know if you if you can still repro after the change above
