### ISSUE TITLE
what would it take to port this to gatsby v3?

### ISSUE THREAD

**Issue by gtnbssn** [colbyfayock/gatsby-starter-leaflet#127]
Sorry this is not really a bug. As a beginner with Gatsby i have been playing with this starter a lot and find it pretty amazing!

As a next exercise i was wondering whether i'd be able to port this to Gatsby v3.

So far i feel like this is above my game.

What would be the steps to do such a thing?

**Comment by colbyfayock** [comment]
hey @gtnbssn i'm not totally sure about the changes to Gatsby v3, whether they're breaking changes or not

you can try starting a new project, run `yarn upgrade --latest`, and then running the app and seeing if that works

ill try to find some time to upgrade the starter

**Comment by gtnbssn** [comment]
Thanks for the quick answer!
It looks like it is mostly working.

I get these two warnings when running gatsby develop:

```
warn Plugin gatsby-plugin-react-leaflet is not compatible with your gatsby version 3.5.0 - It
requires gatsby@^2.0.0
warn Plugin gatsby-plugin-react-leaflet is not compatible with your gatsby version 3.5.0 - It
requires gatsby@^2.0.0
```
And the marker is not showing on the map. I'll dig further into this!

**Comment by gtnbssn** [comment]
Got the marker to show!

Seems like a change in webpack. I updated useConfigureLeaflet hook to add .default after each required image, like this:

```
iconRetinaUrl: require("leaflet/dist/images/marker-icon-2x.png").default,                                                                                          
iconUrl: require("leaflet/dist/images/marker-icon.png").default,     
shadowUrl: require("leaflet/dist/images/marker-shadow.png").default, 
```

**Comment by colbyfayock** [comment]
thanks @gtnbssn i updated the starter to the new versions and fixed the images with your fix

https://github.com/colbyfayock/gatsby-starter-leaflet/commit/7ad18eb162c7de967ea01c948da164b062f715c8

idk if it's related to gatsby v3 but the only weird thing im seeing now is an error when spinning up

```
 ERROR

Unexpected key "pageData" found in preloadedState argument passed to createStore. Expected to find one of the known reducer
keys instead: "nodes", "logs", "pages", "redirects", "schema", "definitions", "staticQueryComponents", "status", "webpack",
"webpackCompilationHash", "config", "lastAction", "jobsV2", "pageDataStats", "components", "babelrc", "jobs", "nodesByType",
"program", "resolvedNodesCache", "nodesTouched", "flattenedPlugins", "pendingPageDataWrites", "schemaCustomization",
"inferenceMetadata", "staticQueriesByTemplate", "queries", "visitedPages", "html", "functions". Unexpected keys will be
ignored.
```

but i can't seem to find anything about it 🤔 

i think we're good for now though it doesnt seem to cause any issues
