### ISSUE TITLE
Find visitor's location and zoom demo header to that location

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/gatsby-starter-leaflet#8]
- Visitor comes from X location
- Map tries to determine their location via the browser API
- If location is allowed and found, zoom in to that location
- If location is not allowed or not found, zoom in to Washington, DC which is current default

**Comment by fuku710** [comment]
I want to try this issue

**Comment by colbyfayock** [comment]
@fuku710 sounds great!
